### ISSUE TITLE
怎么用?

### ISSUE THREAD

**Issue by badboy-tian** [xsfelvis/LintDemo#1]
怎么导入到Android studio啊

**Comment by xsfelvis** [comment]
有两种方案，
（1）将xsflintrules和xsflintaar导入到你的项目，在需要静态检测的moudle中添加 compile project(':xsflint_aar')，只对这个moudle生效
（2）或者将xsflintaar中gradle sysc后生成的jar包放到~/.android/lint中，这样会针对所有工程
推荐使用第一种方案

**Comment by badboy-tian** [comment]
这样呀。多谢多谢 觉得挺不错。代码规范

2016年12月17日 下午12:35，"彩笔学长" <notifications@github.com>写道：
